version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  ml_service:
    build: ./ml_pipeline
    # Add volumes to persist trained models